apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: python-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-consumer
  template:
    metadata:
      labels:
        app: python-consumer
    spec:
      containers:
      - name: consumer
        image: consumer-app:v1
        imagePullPolicy: IfNotPresent