apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    app: python-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-producer
  template:
    metadata:
      labels:
        app: python-producer
    spec:
      containers:
      - name: producer
        image: producer-app:v1
        imagePullPolicy: IfNotPresent