apiVersion: apps/v1
kind: Deployment
metadata:
  name: layer1-deployment
  labels:
    app: layer-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: layer-1
  template:
    metadata:
      labels:
        app: layer-1
    spec:
      containers:
      - name: layer-1
        image: layer1-app:v1
        imagePullPolicy: IfNotPresent