apiVersion: apps/v1
kind: Deployment
metadata:
  name: layer2-deployment
  labels:
    app: layer-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: layer-2
  template:
    metadata:
      labels:
        app: layer-2
    spec:
      containers:
      - name: layer-2
        image: layer2-app:v1
        imagePullPolicy: IfNotPresent